import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import { CalculationResult, CalculationInputs } from '@/types/pseo';

// Define styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#EEE',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#111',
    },
    subtitle: {
        fontSize: 10,
        color: '#666',
        marginTop: 5,
    },
    section: {
        margin: 10,
        padding: 10,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#333',
        textTransform: 'uppercase',
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    label: {
        fontSize: 10,
        color: '#555',
    },
    value: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#000',
    },
    verdictContainer: {
        padding: 15,
        borderRadius: 5,
        marginBottom: 20,
    },
    verdictTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    riskItem: {
        marginBottom: 10,
        padding: 10,
        backgroundColor: '#F9FAFB',
        borderRadius: 4,
    },
    riskTitle: {
        fontSize: 11,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    riskDesc: {
        fontSize: 9,
        color: '#444',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 30,
        right: 30,
        textAlign: 'center',
        fontSize: 8,
        color: '#999',
        borderTopWidth: 1,
        borderTopColor: '#EEE',
        paddingTop: 10,
    },
});

interface ProjectBriefProps {
    inputs: CalculationInputs;
    result: CalculationResult;
}

export const ProjectBriefDocument = ({ inputs, result }: ProjectBriefProps) => {
    const verdict = result.verdict || "CAUTION";

    const verdictColors = {
        GO: { bg: '#ECFDF5', text: '#065F46', label: 'VIABLE DEAL' },
        CAUTION: { bg: '#FFFBEB', text: '#92400E', label: 'PROCEED WITH CAUTION' },
        NOGO: { bg: '#FEF2F2', text: '#991B1B', label: 'HIGH RISK - DO NOT PROCEED' },
    };

    const vStyle = verdictColors[verdict];

    return (
        <Document>
            <Page size="A4" style={styles.page}>

                {/* Header */}
                <View style={styles.header}>
                    <Text style={styles.title}>Project Viability Brief</Text>
                    <Text style={styles.subtitle}>Generated by Import Costs for {inputs.clusterSlug || "General Import"}</Text>
                    <Text style={styles.subtitle}>{new Date().toLocaleDateString()}</Text>
                </View>

                {/* Verdict */}
                <View style={[styles.verdictContainer, { backgroundColor: vStyle.bg }]}>
                    <Text style={[styles.verdictTitle, { color: vStyle.text }]}>{vStyle.label}</Text>
                    <Text style={{ fontSize: 10, color: vStyle.text }}>
                        Based on landed cost analysis and {result.detailedRisks?.length || 0} identified risk factors.
                    </Text>
                </View>

                {/* Financial Summary */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Financial Outlook</Text>
                    <View style={styles.row}>
                        <Text style={styles.label}>Est. Landed Cost (Per Unit)</Text>
                        <Text style={styles.value}>R {result.summary.landed_cost_per_unit_zar.toFixed(2)}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Break-Even Price</Text>
                        <Text style={styles.value}>R {result.breakEvenPrice?.toFixed(2) || "N/A"}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Gross Margin</Text>
                        <Text style={styles.value}>{result.grossMarginPercent !== undefined ? `${result.grossMarginPercent.toFixed(1)}%` : "Not calculated"}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Target Selling Price</Text>
                        <Text style={styles.value}>{inputs.targetSellingPrice ? `R ${inputs.targetSellingPrice.toFixed(2)}` : "Not specified"}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Product Value (FOB/ExWorks)</Text>
                        <Text style={styles.value}>{inputs.currency} {inputs.invoiceValue}</Text>
                    </View>
                </View>

                {/* Risk Assessment */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Risk Assessment</Text>
                    {result.detailedRisks && result.detailedRisks.length > 0 ? (
                        result.detailedRisks.map((risk, i) => (
                            <View key={i} style={styles.riskItem}>
                                <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                                    <Text style={styles.riskTitle}>{risk.title}</Text>
                                    <Text style={{ fontSize: 9, fontWeight: 'bold' }}>{risk.severity}</Text>
                                </View>
                                <Text style={styles.riskDesc}>{risk.description}</Text>
                            </View>
                        ))
                    ) : (
                        <Text style={{ fontSize: 10, color: '#666' }}>No specific high-priority risks identified.</Text>
                    )}
                </View>

                {/* Disclaimer / Footer */}
                <View style={styles.footer}>
                    <Text>This document is for informational purposes only and does not constitute financial or legal advice.
                        Verify all duties and compliance requirements with a licensed customs clearing agent.</Text>
                    <Text style={{ marginTop: 5 }}>www.importcosts.co.za</Text>
                </View>

            </Page>
        </Document>
    );
};
