
/**
 * DocumentContainer.tsx
 * 
 * A visual wrapper that makes the content look like a physical document (A4 ratio)
 * sitting on a desk.
 */
import { cn } from "@/lib/utils";

interface DocumentContainerProps {
    children: React.ReactNode;
    className?: string;
}

export function DocumentContainer({ children, className }: DocumentContainerProps) {
    return (
        <div className="min-h-screen bg-neutral-100 py-12 px-4 sm:px-6 lg:px-8 font-sans">
            <div
                className={cn(
                    "max-w-4xl mx-auto bg-white shadow-xl ring-1 ring-black/5 sm:rounded-sm overflow-hidden min-h-[1100px] relative",
                    className
                )}
            >
                {/* Paper Texture / Header Color Strip */}
                <div className="h-2 w-full bg-neutral-900" />

                {children}

                {/* Footer Watermark */}
                <div className="absolute bottom-8 left-0 right-0 text-center pointer-events-none opacity-50">
                    <p className="text-[10px] text-neutral-300 uppercase tracking-[0.2em]">Generated by ImportCosts.co.za</p>
                </div>
            </div>
        </div>
    );
}
